#!C:\Users\Yash Arora\Desktop\Machine Learning\Kidney Disease Classification MLflow\Kidney-Disease-Classification-MLFlow\kidney\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
